### ISSUE TITLE
测试面向会导致闪退

### ISSUE THREAD

**Issue by kanyeishere** [Karlin-Z/PixelPerfectEx#1]
尝试了几次测试面向都会导致闪退，通过 postman 发请求 setface 也同样会闪退或者 90002

**Comment by RemiliaSCLT** [comment]
我也遇到了这个问题

**Comment by Karlin-Z** [comment]
opcode是错误的，有需求可以自行修改opcode并编译

**Comment by YiweiC1W** [comment]
> opcode是错误的，有需求可以自行修改opcode并编译

K佬能否指个路，关于如何找opcode有无文档可以参考
